apiVersion: v1
kind: Service
metadata:
  name: kube-backend-service
  labels:
    app: kube-backend
    tier: backend   
spec:
  type: ClusterIP
  selector:
    app: kube-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080