apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kube-frontend
  labels:
    app: kube-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-frontend
  template: 
    metadata:
      labels: 
        app: kube-frontend
        tier: frontend
    spec: 
      containers: 
        - name: kube-frontend
          image: adityadevops/kube-frontend:v2
          ports:
            - containerPort: 80